// University of La Laguna
// School of Engineering and Technology
// Bachelor's Degree in Computer Engineering
// Subject: Design and Analysis of Algorithms
// Course: 3rd
// Practice 6: Multi-Source Capacitated Facility Location Problem with Customer Incompatibilities
// Author: Javier Acosta Portocarrero
// Date: 04/04/2026
// File solution.h: declaration file.
// Contains the declaration of the Solution class.

#ifndef SOLUTION_H_
#define SOLUTION_H_

/**
  * @class Solution
  * 
  * @brief Abstract interface class for the solutions generated by algorithms,
  *        thus following the strategy pattern.  
  */
class Solution {
 public:
  virtual ~Solution() = default;
};

#endif